### ISSUE TITLE
类似朋友圈，一张图片怎么写的

### ISSUE THREAD

**Issue by honeycao** [OneWang/IM-WeiChat#1]
多张图可能按照9宫格来定frame，一张图呢？而且是网络图片

**Comment by OneWang** [comment]
看你想怎么显示了, frame 大小需要你自己和后台商量;或者让后台把图片的 frame 返回;

**Comment by honeycao** [comment]
目前是后台没得返回，而且要自己来写，也不能写死，必须根据原图来自动缩放，所以要知道原图尺寸，这个操作占线程，所以不能很好实现，不知道怎么做才好

**Comment by OneWang** [comment]
不好意思啊,这两天有点忙,不知道你的问题解决了吗,我的想法是在你请求下图片之后是可以直接拿到 image.size 的,拿到尺寸之后在进行等比例裁剪就可以啦!

**Comment by honeycao** [comment]
主要是你这里的朋友圈一张图片是怎么处理的，前提是使用的是网络图片，非本地的，等获取到image，那cell基本都出来了，这个问题没有解决

**Comment by OneWang** [comment]
出来就刷新一下
